### ISSUE TITLE
.ximeraserve-local

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/ximeraFirstSteps#15]
Perhaps we should make the so-called "dummy" .ximeraserve a .local-ximeraserve that is used if .ximeraserve is not present. 

This would make it perhaps less likely that a user would push .ximeraserve to the repository, since a default, .local-ximeraserve or maybe:

.ximeraserve-local

(that way the user can just delete "-local"

**Comment by wiobber** [comment]
In fact, the environment variables GPG_KEY and GPG_KEY_ID do OVERWRITE whatever is in .ximeraserve.

Thus, eg in Codespaces, one can set 'Codespace Secrets' named GPG_KEY and GPG_KEY_ID with a personal GPG key, and share them with (codespaces on) chooses repositories.
This solves the issue when using Codespaces (except for properly documenting it, best directly in the ximeraManual it seems).

For 'local' use, we've to figure our a convenient way to set the ENV-variables another way...

**Comment by wiobber** [comment]
now .xmKeyFile is used, and it contains a dummy key.

It is strongly advised to put a proper key in (github-) environment variables or codespace secrets.
But, updating a local copy of .xmKeyFile does work, 
and even committing the new key with 'git add -f' would work.
BUT IT WOULD STORE THE KEY IN THE REPO, which is something you should NOT want to do.
