### ISSUE TITLE
tikz support

### ISSUE THREAD

**Issue by zackreed** [XimeraProject/ximeraFirstSteps#18]
\usepackage{circuitikz}
\usepackage{tikz-3dplot}
\usepackage{mdframed}
\usepackage{tikz-cd}

these are missing from texlive

**Comment by wiobber** [comment]
One could use full_X rather that medium_X  in .devcontainer/docker-compose.yml to get a FULL TexLive installation. 
It will increase the devcontainer size to >7GB.
