### ISSUE TITLE
no preamble.tex

### ISSUE THREAD

**Issue by wiobber** [XimeraProject/ximeraFirstSteps#2]
We should suggest to always use '\input{preamble.tex}, I guess.

(or, implement the automatically-input-preambe-if-present in the ximera/xourse-classes)

**Comment by bartsnapp** [comment]
This is a good idea

**Comment by bartsnapp** [comment]
I think we need to take your suggestion of having global preambles/graphics

**Comment by wiobber** [comment]
Added in ximeraLatex now  (development branch)
