### ISSUE TITLE
ANSWER BROKEN on this page

### ISSUE THREAD

**Issue by clairemerriman** [XimeraProject/ximeraFirstSteps#27]
ANSWER BROKEN. 

issue with answers in the new layout? Does not occur in [current production server version](https://ximera.osu.edu/firststeps24/aFirstXourse/aFirstFolder/exercises/someExercises)

Issue here: https://github.com/XimeraProject/ximeraFirstSteps/blob/598b26d9688f258f800aa04f0e8e6813724f0fc9/aFirstFolder/exercises/someExercises.tex#L19

[This version](https://github.com/XimeraProject/ximeraFirstSteps/blob/598b26d9688f258f800aa04f0e8e6813724f0fc9/aFirstFolder/aFirstActivity.tex#L80) of the question here works as expected. The only difference appears to be inline vs display math.

**Comment by bartsnapp** [comment]
The offending page is here:

https://set.kuleuven.be/voorkennis/firststeps24/aFirstXourseVariant/aFirstFolder/exercises/someExercises

type in 100 -- it doesn't work!

**Comment by bartsnapp** [comment]
This is a cookie issue!
